spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voll_db
    username: voll
    password: voll
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect