CREATE TABLE MEDICOS(
    ID SERIAL NOT NULl ,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CRM VARCHAR(6) NOT NULL,
    ESPECIALIDADE VARCHAR(100) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    NUMERO VARCHAR(20) ,
    CIDADE VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,

    PRIMARY KEY (ID)
);