CREATE TABLE PACIENTES(
    ID SERIAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    NUMERO VARCHAR(20),
    CIDADE VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (ID)
);
