CREATE TABLE CONSULTAS (
    ID SERIAL NOT NULL,
    MEDICO_ID BIGINT NOT NULL,
    PACIENTE_ID BIGINT NOT NULL,
    DATA DATE NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (MEDICO_ID) REFERENCES MEDICOS(ID),
    FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES(ID)
)